import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { Providers } from './providers'

export interface RootLayoutProps {
    children: ReactNode
}

export const metadata: Metadata = {
    icons: {
        icon: '/favicon.ico',
    },
    // title: 'VEZO',
    // description: 'Generated by create next app'
}

export default async function RootLayout(props: RootLayoutProps) {

    const { children } = props

    return (
        <html data-theme='light' lang='en'>
            <body>
                <Providers>
                    {children}
                </Providers>
            </body>
        </html>
    )
}
